from abc import ABC, abstractmethod
import numpy as np
from typing import Dict, Any

class AbstractVoiceModel(ABC):
    @abstractmethod
    def predict(self, features: np.ndarray) -> Dict[str, Any]:
        """
        Must return:
        {"verdict": "HUMAN"|"AI"|"UNCERTAIN", "risk_score": float, "confidence": float, "evidence": dict}
        """
        pass

class DummyVoiceModel(AbstractVoiceModel):
    """
    PLACEHOLDER MODEL.
    Generates a deterministic risk score based on the mathematical properties of the feature vector.
    Must be swapped out for the real PyTorch/Wav2Vec2 implementation.
    """
    def predict(self, features: np.ndarray) -> Dict[str, Any]:
        # Deterministic pseudo-random generation based on input features
        mean_val = float(np.mean(features))
        variance_val = float(np.var(features))
        
        # Create a stable seed from the feature math
        seed = int(abs(mean_val + variance_val) * 100000)
        risk_score = (seed % 1000) / 1000.0  # Float between 0.0 and 0.999
        
        if risk_score > 0.60:
            verdict = "AI"
        elif risk_score < 0.40:
            verdict = "HUMAN"
        else:
            verdict = "UNCERTAIN"
            
        return {
            "verdict": verdict,
            "risk_score": risk_score,
            "confidence": 0.85,
            "evidence": {
                "feature_mean": mean_val,
                "feature_variance": variance_val,
                "note": "Generated by Dummy Model"
            }
        }

# Singleton instance to be used across the app
model_instance = DummyVoiceModel()